# generated by run-prototype.ps1; runs the fixture generator and records its exit code
$ErrorActionPreference = 'Continue'
$genCode = 0
& 'C:\Users\qnhxx\Documents\AI-Projects\Code\pi-subagent\.scratch\pi-subagent-slimming\prototype\fixture-generator.ps1' -OutDir 'C:\Users\qnhxx\Documents\AI-Projects\Code\pi-subagent\.scratch\pi-subagent-slimming\prototype\_out' -Scenario 'all' -Runs 4 -VolumeEvents 50000 -Seed 0 -Rate 0 -GatePostSleepMs 2000 -Stream
if (-not $?) { $genCode = 1 }
if (($LASTEXITCODE -is [int]) -and ($LASTEXITCODE -ne 0)) { $genCode = $LASTEXITCODE }
[System.IO.File]::WriteAllText('C:\Users\qnhxx\Documents\AI-Projects\Code\pi-subagent\.scratch\pi-subagent-slimming\prototype\_out\generator.exitcode.txt', [string]$genCode)
exit $genCode
